import assert from "node:assert/strict";
import test from "node:test";
import { downloadPackageAssets, offlineTile, removePackageMetadata, renderOfflineMapHtml } from "../src/offline-pipeline.js";

const manifest = { analysisJobId: "a", estimatedSizeBytes: 20, map: { tilePlan: { provider: { id: "fixture", attribution: "test fixture" }, maxZoom: 1, tiles: [{ key: "fixture/1/0/0", z: 1, x: 0, y: 0, url: "/tile" }] } }, userRecords: { attachments: [{ id: "att", downloadUrl: "/attachment", contentType: "image/png" }] } };
test("downloads tiles and attachment binaries, checkpoints, retries, and renders offline lookup", async () => { let attempts = 0; const checkpoints = []; const result = await downloadPackageAssets(structuredClone(manifest), { retries: 1, checkpoint: async (value) => checkpoints.push(value.downloadState.status), fetchAsset: async (asset) => { attempts += 1; if (asset.kind === "tile" && attempts === 1) throw new Error("retry"); return { dataUrl: "data:image/png;base64,AA==", sizeBytes: 1, contentType: "image/png" }; } }); assert.equal(attempts, 3); assert.equal(result.downloadState.status, "ready"); assert.ok(offlineTile(result, "fixture", 1, 0, 0)); assert.match(renderOfflineMapHtml(result), /data:image\/png/); assert.ok(checkpoints.includes("downloading")); });
test("resumes by skipping cached assets", async () => { const partial = structuredClone(manifest); partial.cachedAssets = { "fixture/1/0/0": { dataUrl: "data:image/png;base64,AA==", sizeBytes: 1 } }; let calls = 0; await downloadPackageAssets(partial, { fetchAsset: async () => { calls += 1; return { dataUrl: "data:image/png;base64,AA==", sizeBytes: 1 }; } }); assert.equal(calls, 1); });
test("cancellation preserves prior checkpoints", async () => { const controller = new AbortController(); controller.abort(); await assert.rejects(downloadPackageAssets(structuredClone(manifest), { signal: controller.signal, fetchAsset: async () => ({}) }), { name: "AbortError" }); });
test("enforces actual package size limit", async () => { const limited = structuredClone(manifest); limited.maxPackageBytes = 1; await assert.rejects(downloadPackageAssets(limited, { fetchAsset: async () => ({ dataUrl: "data:x", sizeBytes: 2 }) }), /size limit/); });
test("removal drops only the selected package metadata", () => assert.deepEqual(removePackageMetadata({ a: {}, b: {} }, "a"), { b: {} }));
