export const DEFAULT_LAYER_PREFERENCES={basemap:"satellite",analysis:{boundary:true,waypoints:true,features:true,relationships:true},field:{notes:true,visited_points:true,breadcrumbs:true,current_location:true},gis:{parcels:false,hillshade:false,elevation:false},team:{team_positions:true}};
export function normalizeLayerPreferences(value={}){const source=value&&typeof value==="object"?value:{};const basemap=["satellite","hybrid","topographic"].includes(source.basemap)?source.basemap:"satellite";const group=(name)=>Object.fromEntries(Object.entries(DEFAULT_LAYER_PREFERENCES[name]).map(([key,fallback])=>[key,name==="analysis"&&key==="boundary"?true:typeof source[name]?.[key]==="boolean"?source[name][key]:fallback]));return{basemap,analysis:group("analysis"),field:group("field"),gis:group("gis"),team:group("team")};}
export function setBasemap(preferences,basemap){return normalizeLayerPreferences({...preferences,basemap});}
export function toggleLayer(preferences,group,key){const next=normalizeLayerPreferences(preferences);if(!(key in next[group])||(group==="analysis"&&key==="boundary"))return next;return{...next,[group]:{...next[group],[key]:!next[group][key]}};}
export function breadcrumbLayerStatus({visible=true,loading=false,unavailable=false,hasRecordedPoints=false,recording=false,hasSelectedAnalysis=true}={}){if(!hasSelectedAnalysis)return visible?"Visible":"Hidden";if(recording)return`Recording · ${visible?"Visible":"Hidden"}`;if(loading)return"Loading trails…";if(unavailable&&!hasRecordedPoints)return"Trail status unavailable";if(!hasRecordedPoints)return"None recorded";return visible?"Visible":"Hidden";}
export function shouldShowBreadcrumbEmptyState({visible=true,loading=false,unavailable=false,hasRecordedPoints=false,recording=false,hasSelectedAnalysis=true}={}){return Boolean(hasSelectedAnalysis&&visible&&!loading&&!unavailable&&!hasRecordedPoints&&!recording);}
export function shouldApplyHydratedActiveBreadcrumb({requestId,currentRequestId,startRevision,currentRevision}={}){return requestId===currentRequestId&&startRevision===currentRevision;}
export function layerAvailability({providers=[],hasNotes=false,hasVisited=false,hasBreadcrumbs=false,hasCurrentLocation=false,hasTeamPositions=false}={}){const types=new Set(providers.flatMap((provider)=>provider.layers||[]).map((layer)=>layer.type));return{notes:hasNotes,visited_points:hasVisited,breadcrumbs:hasBreadcrumbs,current_location:hasCurrentLocation,parcels:types.has("parcels"),hillshade:types.has("hillshade"),elevation:types.has("elevation"),team_positions:hasTeamPositions};}
export function offlineLayerPolicy(layer,providers=[]){if(["boundary","waypoints","features","relationships","notes","visited_points","breadcrumbs","current_location"].includes(layer))return"package";const configured=providers.flatMap((provider)=>provider.layers||[]).find((item)=>item.type===layer);return configured?.offlinePermitted===true?"provider-permitted":"online-only";}
