// @ts-nocheck -- Expo sensor DTOs are runtime-validated and shared with the JS navigation core.
import React,{useEffect,useMemo,useState}from"react";
import{Linking,Platform,Pressable,StyleSheet,Text,View}from"react-native";
import * as Location from"expo-location";import * as SecureStore from"expo-secure-store";import * as Crypto from"expo-crypto";
import{ACTIVE_KEY,BREADCRUMB_TASK}from"./navigation-background";import{createBreadcrumb,navigationSnapshot,transitionBreadcrumb}from"./navigation-core";
import{createBreadcrumbRecord,deleteBreadcrumbRecord,updateBreadcrumbRecord}from"./api";
export function NavigationPanel(props: any): any;
export function NavigationPanel({analysisJobId,waypoints=[],selectedTarget=null,onSelectTarget}){const[selected,setSelected]=useState(null),[location,setLocation]=useState(null),[follow,setFollow]=useState(false),[track,setTrack]=useState(null),[message,setMessage]=useState("");useEffect(()=>{setSelected(selectedTarget?.geometry?.type==="Point"?selectedTarget:null)},[analysisJobId,selectedTarget?.id]);const destination=selected?.geometry?.coordinates?{longitude:selected.geometry.coordinates[0],latitude:selected.geometry.coordinates[1]}:null;const nav=useMemo(()=>navigationSnapshot(location,destination,{arrivalRadiusMeters:30}),[location,destination]);
async function locate(){const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=="granted"){setMessage("Location permission is required only while navigation is active.");return;}const next=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setLocation({...next.coords,recordedAt:new Date(next.timestamp).toISOString()});setFollow(true);await Location.watchPositionAsync({accuracy:Location.Accuracy.High,timeInterval:5000,distanceInterval:5},(value)=>setLocation({...value.coords,recordedAt:new Date(value.timestamp).toISOString()}));}
async function persist(next){setTrack(next);if(next)await SecureStore.setItemAsync(ACTIVE_KEY,JSON.stringify({...next,analysisJobId}));else await SecureStore.deleteItemAsync(ACTIVE_KEY);}
async function start(){if(!analysisJobId){setMessage("Save this analysis before recording a breadcrumb.");return;}await locate();const background=await Location.requestBackgroundPermissionsAsync();if(background.status!=="granted")setMessage("Background permission denied; tracking remains foreground-only.");const next=createBreadcrumb({id:Crypto.randomUUID(),name:"Field breadcrumb"});await persist(next);await createBreadcrumbRecord(analysisJobId,next).catch(()=>setMessage("Breadcrumb is pending synchronization."));if(background.status==="granted")await Location.startLocationUpdatesAsync(BREADCRUMB_TASK,{accuracy:Location.Accuracy.High,distanceInterval:5,timeInterval:5000,showsBackgroundLocationIndicator:true,foregroundService:{notificationTitle:"HuntIntel breadcrumb active",notificationBody:"Tap the app to pause or stop tracking."}});}
async function action(name){const next=transitionBreadcrumb(track,name,name==="rename"?{name:`Field breadcrumb ${new Date().toLocaleTimeString()}`}:{},new Date().toISOString());await persist(next);if(name==="delete"){await deleteBreadcrumbRecord(analysisJobId,track.id).catch(()=>setMessage("Delete is pending synchronization."));setTrack(null);}else await updateBreadcrumbRecord(analysisJobId,track.id,{name:next.name,status:next.status,endedAt:next.endedAt}).catch(()=>setMessage("Breadcrumb change is pending synchronization."));if((name==="finish"||name==="delete")&&await Location.hasStartedLocationUpdatesAsync(BREADCRUMB_TASK))await Location.stopLocationUpdatesAsync(BREADCRUMB_TASK);}
async function handoff(){if(!destination)return;const query=`${destination.latitude},${destination.longitude}`;await Linking.openURL(Platform.OS==="ios"?`http://maps.apple.com/?daddr=${query}`:`https://www.google.com/maps/dir/?api=1&destination=${query}`);}
return <View style={s.card}><Text style={s.title}>Field Navigation</Text><Text style={s.meta}>Location starts only when requested. Guidance and destination line are straight-line; confirm field conditions.</Text><View style={s.row}><Button label="Center / Follow" onPress={locate}/><Button label={follow?"Following":"Follow off"} onPress={()=>setFollow(!follow)}/></View>{location&&<Text style={s.meta}>Accuracy ±{Math.round(location.accuracy||0)} m · updated {new Date(location.recordedAt).toLocaleTimeString()} {nav?.stale?"· STALE":""}{location.altitude!=null?` · altitude ${Math.round(location.altitude)} m`:""}{location.heading!=null?` · heading ${Math.round(location.heading)}°`:""}{location.speed!=null?` · speed ${location.speed.toFixed(1)} m/s`:""}</Text>}<Text style={s.meta}>Destination</Text>{waypoints.map((w)=><Button key={w.id} label={w.title||w.id} onPress={()=>{setSelected(w);onSelectTarget?.(w)}} primary={selected?.id===w.id}/>)}{nav&&<><View style={s.line}/><Text style={s.metric}>{Math.round(nav.distanceMeters)} m · {Math.round(nav.bearingDegrees)}° · arrival radius {nav.arrivalRadiusMeters} m {nav.arrived?"· ARRIVED":""}</Text><Button label="Open road navigation" onPress={handoff}/></>}<View style={s.row}>{!track&&<Button label="Start Breadcrumb" onPress={start} primary/>}{track?.status==="active"&&<Button label="Pause" onPress={()=>action("pause")}/>} {track?.status==="paused"&&<Button label="Resume" onPress={()=>action("resume")} primary/>}{track&&track.status!=="finished"&&<Button label="Finish / Stop" onPress={()=>action("finish")}/>} {track&&<Button label="Rename" onPress={()=>action("rename")}/>} {track&&<Button label="Delete" onPress={()=>action("delete")}/>}</View>{track&&<Text style={s.active}>● Background breadcrumb {track.status}. Use Finish / Stop to end.</Text>}{message&&<Text style={s.warn}>{message}</Text>}</View>;}
function Button({label,onPress,primary}){return <Pressable onPress={onPress} style={[s.button,primary&&s.primary]}><Text style={s.buttonText}>{label}</Text></Pressable>}const s=StyleSheet.create({card:{backgroundColor:"#111812",padding:14,borderRadius:16,gap:8},title:{color:"#fff",fontWeight:"800",fontSize:18},meta:{color:"#aab7a5"},metric:{color:"#f0d293",fontWeight:"700"},line:{height:3,backgroundColor:"#5aa7ff",borderRadius:3},row:{flexDirection:"row",flexWrap:"wrap",gap:8},button:{backgroundColor:"#283329",padding:10,borderRadius:999},primary:{backgroundColor:"#8e6b32"},buttonText:{color:"#fff",fontWeight:"700"},active:{color:"#8ed17c",fontWeight:"700"},warn:{color:"#e3b26d"}});
