import React,{useEffect,useMemo,useRef,useState}from"react";
import*as SecureStore from"expo-secure-store";
import*as Crypto from"expo-crypto";
import{ActivityIndicator,Alert,Pressable,StyleSheet,Text,View}from"react-native";
import{ErrorCode,type Purchase,useIAP}from"react-native-iap";
import{createPaymentAttempt,fetchAnalysis,fetchAnalysisPurchase,reconcileAnalysisPurchase,submitPaidAnalysis,verifyPaymentAttempt}from"./api";
import{productIdForPurchase,selectPlatformPaymentProvider,STORE_PRODUCT_IDS}from"./payment-provider";
import{clearPaymentRecoveryHint,savePaymentRecoveryHint}from"./payment-recovery";

const ANALYSIS_LIMIT_CODE="ANALYSIS_LIBRARY_LIMIT_REACHED",ANALYSIS_LIMIT_TITLE="My Analyses is full",ANALYSIS_LIMIT_MESSAGE="Delete at least one saved analysis before starting another. Your payment remains confirmed and you will not be charged again.";
type PaymentState="idle"|"purchasing"|"verifying"|"payment_pending"|"payment_confirmed"|"restoring"|"submitting"|"processing"|"complete"|"recoverable_failure"|"canceled"|"failed";

export function PaymentGate({initial,onComplete,onBack,onQuoteInvalid,onLibraryLimit,onPurchaseChange}:{initial:any;onComplete:(analysis:any)=>void;onBack:()=>void;onQuoteInvalid?:()=>void;onLibraryLimit?:()=>void;onPurchaseChange?:(purchase:any)=>void}){
 const[purchase,setPurchase]=useState(initial),[state,setState]=useState<PaymentState>(["active","consumed"].includes(initial?.entitlement?.status)?"payment_confirmed":"idle"),[message,setMessage]=useState("Payment is required before HTIE starts."),attemptRequest=useRef(false),handled=useRef(new Set<string>()),nativePurchase=useRef<Purchase|null>(null),autoStarted=useRef(false),mounted=useRef(true);
 const provider=selectPlatformPaymentProvider(purchase),productId=useMemo(()=>productIdForPurchase(purchase),[purchase?.draft?.tierKey,purchase?.quote?.providerProductId]),attempt=purchase.paymentAttempt;
 const{connected,products,availablePurchases,fetchProducts,getAvailablePurchases,requestPurchase,finishTransaction}=useIAP({onPurchaseSuccess:value=>{void handleNativePurchase(value);},onPurchaseError:error=>{if(error.code===ErrorCode.E_USER_CANCELLED){setState("canceled");setMessage("Payment was canceled. No analysis started.");}else{setState("failed");setMessage(error.message||"Google Play purchase failed.");}}});
 const storeProduct=products.find(value=>value.id===productId);
 useEffect(()=>()=>{mounted.current=false;},[]);
 useEffect(()=>{if(!connected)return;void fetchProducts({skus:Object.values(STORE_PRODUCT_IDS),type:"inapp"});void getAvailablePurchases();},[connected]);
 useEffect(()=>{const value=availablePurchases.find(item=>item.productId===productId);if(value)void handleNativePurchase(value);},[availablePurchases,productId]);
 useEffect(()=>{if(["active","consumed"].includes(purchase.entitlement?.status)&&!autoStarted.current){autoStarted.current=true;void startAnalysis(purchase);}},[purchase.entitlement?.status]);
 const update=(next:any)=>{if(!mounted.current)return;setPurchase(next);onPurchaseChange?.(next);};
 const errorText=(error:any)=>{if(error?.code==="PRICE_CHANGED")onQuoteInvalid?.();return error instanceof Error?error.message:"Payment failed.";};
 async function ensureAttempt(){if(attempt&&["created","pending"].includes(attempt.status))return attempt;if(purchase.entitlement?.status==="active")return null;if(!provider?.enabled)throw new Error("The configured Google Play payment provider is disabled in this build.");if(attemptRequest.current)throw new Error("Payment initialization is already in progress.");attemptRequest.current=true;try{const result=await createPaymentAttempt(purchase.draft.draftId,{provider:provider.provider,idempotencyKey:Crypto.randomUUID()}),next={...purchase,...result};update(next);return result.paymentAttempt;}finally{attemptRequest.current=false;}}
 async function beginNativePurchase(){setState("purchasing");setMessage("Opening Google Play…");try{const current=await ensureAttempt();if(!current)return void startAnalysis(purchase);await savePaymentRecoveryHint(SecureStore,{draftId:purchase.draft.draftId,attemptId:current.attemptId,productId});const accountId=await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256,purchase.draft.draftId);await requestPurchase({request:{android:{skus:[productId],obfuscatedAccountIdAndroid:accountId}},type:"inapp"});}catch(error){setState("failed");setMessage(errorText(error));}}
 async function handleNativePurchase(value:Purchase){
  if(value.productId!==productId)return;nativePurchase.current=value;
  if((value as any).purchaseStateAndroid===2){setState("payment_pending");setMessage("Your Google Play payment is pending. The analysis will start after Google confirms it.");return;}
  const identity=value.purchaseToken||value.transactionId||value.id||"";if(!identity||handled.current.has(identity))return;
  handled.current.add(identity);setState("payment_confirmed");setMessage("Your terrain analysis has been paid for successfully. We're restoring your analysis and starting it now.");
  try{const current=await ensureAttempt();if(!current)return void startAnalysis(purchase);setState("verifying");const result=await verifyPaymentAttempt(purchase.draft.draftId,current.attemptId,{purchaseToken:value.purchaseToken,transactionId:value.transactionId,productId:value.productId});if(result.paymentAttempt?.status==="pending"){handled.current.delete(identity);setState("payment_pending");setMessage("Your Google Play payment is pending. The analysis will start after Google confirms it.");return;}if(result.entitlement?.status!=="active")throw new Error("The Google Play purchase has not been confirmed by the server.");update(result);setState("restoring");await finishTransaction({purchase:value,isConsumable:true});await startAnalysis(result);}catch(error){handled.current.delete(identity);setState("recoverable_failure");setMessage(`Payment confirmed\nYour payment was successful, but the analysis could not start automatically.\nYou will not be charged again.\n${errorText(error)}`);}
 }
 async function waitForJob(draftId:string){for(let count=0;mounted.current&&count<120;count++){const current=await fetchAnalysisPurchase(draftId);update(current);const id=current.draft?.analysisJobId||current.entitlement?.analysisJobId;if(id)return fetchAnalysis(id);if(current.draft?.failureCode)throw new Error("The analysis needs attention before it can continue.");await new Promise(resolve=>setTimeout(resolve,2000));}throw new Error("Analysis is still processing. You can resume it from Pending Analyses.");}
 async function startAnalysis(current=purchase){if(current.entitlement?.status!=="active"&&current.entitlement?.status!=="consumed")return;setState("submitting");setMessage("Payment confirmed. Starting terrain analysis…");try{const result=await submitPaidAnalysis(current.draft.draftId,"native_auto");setState("processing");setMessage("HTIE is generating features, relationships, waypoints, and a deterministic report.");const id=result.analysisJobId||result.draft?.analysisJobId;const analysis=result.features?result:id?await fetchAnalysis(id):await waitForJob(current.draft.draftId);await clearPaymentRecoveryHint(SecureStore);setState("complete");onComplete(analysis);}catch(error:any){if(error?.code===ANALYSIS_LIMIT_CODE)Alert.alert(ANALYSIS_LIMIT_TITLE,ANALYSIS_LIMIT_MESSAGE,[{text:"Go to My Analyses",onPress:onLibraryLimit},{text:"Cancel",style:"cancel"}]);setState("recoverable_failure");setMessage(`Payment confirmed\nYour payment was successful, but the analysis could not start automatically.\nYou will not be charged again.\n${errorText(error)}`);}}
 async function reconcile(){setState("restoring");try{const result=await reconcileAnalysisPurchase(purchase.draft.draftId);update(result);if(result.entitlement?.status==="active"||result.entitlement?.status==="consumed")await startAnalysis(result);else{setState(result.paymentAttempt?.status==="pending"?"payment_pending":"idle");setMessage(`Server payment status: ${result.paymentAttempt?.status||result.draft.status}.`);}}catch(error){setState("failed");setMessage(errorText(error));}}
 const blocking=new Set<PaymentState>(["purchasing","verifying","payment_pending","payment_confirmed","restoring","submitting","processing"]),paid=Boolean(purchase.entitlement&&["active","consumed"].includes(purchase.entitlement.status));
 return<View style={s.card}><Text style={s.eyebrow}>ONE-TIME ANALYSIS UNLOCK</Text><Text style={s.title}>{state==="payment_confirmed"||paid?"Payment Successful":purchase.quote.label}</Text><Text style={s.price}>{storeProduct?.displayPrice||"Loading Google Play price…"}</Text><Text style={s.text}>{Number(purchase.quote.acreage).toLocaleString()} server-calculated acres</Text>{blocking.has(state)&&<ActivityIndicator color="#d0a65d"/>}<Text style={s.meta}>{message}</Text><View style={s.row}>{state==="idle"&&!paid&&<Button label={`Purchase${storeProduct?` — ${storeProduct.displayPrice}`:""}`} primary disabled={!connected||!storeProduct} onPress={beginNativePurchase}/>} {state==="recoverable_failure"&&(paid?<Button label="Retry Starting Analysis" primary onPress={()=>startAnalysis(purchase)}/>:nativePurchase.current?<Button label="Retry Verification" primary onPress={()=>handleNativePurchase(nativePurchase.current!)}/>:null)} {(state==="failed"||state==="canceled")&&nativePurchase.current&&<Button label="Retry Verification" primary onPress={()=>handleNativePurchase(nativePurchase.current!)}/>} {!blocking.has(state)&&<Button label="Restore / Reconcile" onPress={reconcile}/>} {!blocking.has(state)&&!paid&&<Button label="Back to Setup" onPress={onBack}/>}</View></View>;
}
function Button({label,onPress,primary,disabled}:any){return<Pressable disabled={disabled} onPress={onPress} style={[s.button,primary&&s.primary,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>}
const s=StyleSheet.create({card:{backgroundColor:"#182019",borderRadius:24,padding:18,gap:12},eyebrow:{color:"#d0a65d",letterSpacing:1.5,fontSize:11},title:{color:"#f0f3ea",fontWeight:"800",fontSize:24},price:{color:"#d0a65d",fontWeight:"800",fontSize:20},text:{color:"#e3e8dd"},meta:{color:"#9cab97",lineHeight:20},row:{flexDirection:"row",flexWrap:"wrap",gap:10},button:{backgroundColor:"#283329",borderRadius:999,paddingHorizontal:14,paddingVertical:10},primary:{backgroundColor:"#d0a65d"},disabled:{opacity:.4},buttonText:{color:"#f5f2e9",fontWeight:"700"}});
