import React,{useState}from"react";
import{Pressable,StyleSheet,Text,View}from"react-native";
import*as Crypto from"expo-crypto";
import{createPaymentAttempt,reconcileAnalysisPurchase,submitPaidAnalysis,verifyPaymentAttempt}from"./api";

export function PaymentGate({initial,onComplete,onBack}:{initial:any;onComplete:(analysis:any)=>void;onBack:()=>void}){const[purchase,setPurchase]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState("Payment is required before HTIE starts."),[retry,setRetry]=useState(false);const attempt=purchase.paymentAttempt;
 async function ensureAttempt(){if(attempt&&["created","pending"].includes(attempt.status))return attempt;const result=await createPaymentAttempt(purchase.draft.draftId,{provider:purchase.provider.provider,idempotencyKey:Crypto.randomUUID()});setPurchase((current:any)=>({...current,...result}));return result.paymentAttempt;}
 async function analyze(){setBusy(true);setMessage("Payment confirmed. Starting HTIE analysis…");try{const result=await submitPaidAnalysis(purchase.draft.draftId);if(result.alreadySubmitted&&!result.analysisJobId){setMessage("Analysis submission is already in progress.");return;}onComplete(result);}catch(error){setRetry(true);setMessage(`${error instanceof Error?error.message:"Analysis submission failed."} Retry does not require another purchase.`);}finally{setBusy(false)}}
 async function scenario(value:string){setBusy(true);setMessage(`Processing ${value} development payment…`);try{const current=await ensureAttempt(),result=await verifyPaymentAttempt(purchase.draft.draftId,current.attemptId,{scenario:value});setPurchase((previous:any)=>({...previous,...result}));const status=result.paymentAttempt.status;if(result.entitlement?.status==="active"){setMessage("One-time purchase verified.");await analyze();}else setMessage(status==="pending"?"Payment remains pending.":status==="canceled"?"Payment was canceled. No analysis started.":"Payment failed or expired. No analysis started.");}catch(error){setMessage(error instanceof Error?error.message:"Payment failed.");}finally{setBusy(false)}}
 async function reconcile(){setBusy(true);try{const result=await reconcileAnalysisPurchase(purchase.draft.draftId);setPurchase((previous:any)=>({...previous,...result}));setMessage(`Server payment status: ${result.paymentAttempt?.status||result.draft.status}.`);if(result.entitlement?.status==="active")setRetry(true);}catch(error){setMessage(error instanceof Error?error.message:"Reconciliation failed.");}finally{setBusy(false)}}
 const button=(label:string,onPress:()=>void,primary=false)=><Pressable disabled={busy} style={[s.button,primary&&s.primary,busy&&s.disabled]} onPress={onPress}><Text style={primary?s.primaryText:s.text}>{label}</Text></Pressable>;
 return<View style={s.card}><Text style={s.eyebrow}>ONE-TIME ANALYSIS UNLOCK</Text><Text style={s.title}>{purchase.quote.label} — {purchase.quote.displayPrice}</Text><Text style={s.text}>{Number(purchase.quote.acreage).toLocaleString()} server-calculated acres</Text><Text style={s.meta}>One-time purchase. Permanently unlocks this completed terrain analysis for your account. This is not a subscription and does not unlock future analyses.</Text><Text style={s.meta}>Provider: {purchase.provider.provider} · Status: {attempt?.status||purchase.draft.status}</Text>{purchase.provider.enabled?<View style={s.row}>{button("Complete Test Payment",()=>scenario("success"),true)}{button("Pending",()=>scenario("pending"))}{button("Fail",()=>scenario("failed"))}{button("Cancel",()=>scenario("canceled"))}{button("Timeout",()=>scenario("timeout"))}</View>:<Text style={s.error}>The configured production payment provider is disabled in this build.</Text>}<View style={s.row}>{(retry||purchase.entitlement?.status==="active")&&button("Retry Analysis — No Repurchase",analyze,true)}{button("Restore / Reconcile",reconcile)}{button("Back to Setup",onBack)}</View><Text style={s.meta}>{message}</Text></View>}
const s=StyleSheet.create({card:{backgroundColor:"#182019",borderRadius:24,padding:18,gap:12},eyebrow:{color:"#d0a65d",letterSpacing:2,fontSize:12},title:{color:"#f0f3ea",fontSize:22,fontWeight:"700"},text:{color:"#f0f3ea"},meta:{color:"#9cab97",lineHeight:20},error:{color:"#d68375"},row:{flexDirection:"row",flexWrap:"wrap",gap:10},button:{backgroundColor:"#243025",borderRadius:999,paddingHorizontal:16,paddingVertical:12},primary:{backgroundColor:"#d0a65d"},primaryText:{color:"#1f180f",fontWeight:"700"},disabled:{opacity:.45}});
