import React, { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import * as FileSystem from "expo-file-system";
import * as Sharing from "expo-sharing";

import { fetchPdfReportDownload, generatePdfReport } from "./api";
import { safeLocalPdfFilename, togglePdfOption } from "./pdf-report";

const INITIAL={includeFieldNotes:false,includeAttachments:false,includeBreadcrumbs:false};
export function PdfReportPanel({analysisJobId}:{analysisJobId:string}) {
 const[options,setOptions]=useState<any>(INITIAL),[artifact,setArtifact]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const generate=async()=>{setBusy(true);setMessage("Generating a private PDF report…");try{const result=await generatePdfReport(analysisJobId,options);setArtifact(result.artifact);setMessage(result.reused?"The current report version was reused.":"PDF report generated.");}catch(error){setMessage(error instanceof Error?error.message:"PDF generation failed.");}finally{setBusy(false)}};
 const share=async()=>{let uri="";setBusy(true);setMessage("Preparing a secure download…");try{const result=await fetchPdfReportDownload(analysisJobId,artifact.exportId);uri=`${FileSystem.cacheDirectory}${safeLocalPdfFilename(result.filename)}`;await FileSystem.downloadAsync(result.downloadUrl,uri);if(!await Sharing.isAvailableAsync())throw new Error("Sharing is unavailable on this device.");await Sharing.shareAsync(uri,{mimeType:"application/pdf",UTI:"com.adobe.pdf",dialogTitle:"Share HuntIntel PDF Report"});setMessage("PDF shared from temporary app storage.");}catch(error){setMessage(error instanceof Error?error.message:"PDF download failed.");}finally{if(uri)await FileSystem.deleteAsync(uri,{idempotent:true}).catch(()=>{});setBusy(false)}};
 const option=(key:string,label:string)=><Pressable accessibilityRole="checkbox" accessibilityState={{checked:Boolean(options[key])}} style={s.option} onPress={()=>setOptions((current:any)=>togglePdfOption(current,key))}><Text style={s.check}>{options[key]?"☑":"☐"}</Text><Text style={s.text}>{label}</Text></Pressable>;
 return <View style={s.panel}><Text style={s.eyebrow}>VERSIONED PRIVATE ARTIFACT</Text><Text style={s.title}>PDF Report</Text><Text style={s.meta}>Generated from this saved analysis. Optional field records remain separate from HTIE Engine Findings.</Text>{option("includeFieldNotes","Personal notes and visit status")}{option("includeAttachments","Attachment metadata and photo thumbnails")}{option("includeBreadcrumbs","Breadcrumb summaries")}<View style={s.row}><Pressable style={s.primary} disabled={busy} onPress={generate}><Text style={s.primaryText}>{busy?"Working…":"Generate PDF"}</Text></Pressable>{artifact?.status==="ready"&&<Pressable style={s.button} disabled={busy} onPress={share}><Text style={s.text}>Download / Share</Text></Pressable>}</View>{message?<Text style={s.meta}>{message}</Text>:null}{artifact?<Text style={s.meta}>Status: {artifact.status}{artifact.sizeBytes?` · ${Math.ceil(artifact.sizeBytes/1024)} KiB`:""}</Text>:null}</View>;
}
const s=StyleSheet.create({panel:{backgroundColor:"#0f140f",padding:14,borderRadius:16,gap:10,marginTop:10},eyebrow:{color:"#d0a65d",fontSize:11,letterSpacing:1.5},title:{color:"#f0f3ea",fontSize:20,fontWeight:"700"},meta:{color:"#9cab97",lineHeight:19},option:{flexDirection:"row",gap:8,alignItems:"center"},check:{color:"#d0a65d",fontSize:20},text:{color:"#f0f3ea"},row:{flexDirection:"row",flexWrap:"wrap",gap:10},button:{backgroundColor:"#243025",borderRadius:999,paddingHorizontal:16,paddingVertical:12},primary:{backgroundColor:"#d0a65d",borderRadius:999,paddingHorizontal:16,paddingVertical:12},primaryText:{color:"#1f180f",fontWeight:"700"}});
