import React, { useEffect, useRef, useState } from "react";
import * as Crypto from "expo-crypto";
import * as Location from "expo-location";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { createSarAssignment, createSarObservationOffline, endSarSession, fetchActiveSarSession, fetchSarPositions, fetchSarSession, publishSarPosition, startSarSession, startSarSharing, stopSarSharing, updateSarAssignmentOffline } from "./api";
import { nextSarPosition, sarPositionState } from "./sar-core";
import { startSarBackground, stopSarBackground } from "./sar-background";

export function SarScreen({onClose}:{onClose:()=>void}) {
 const [teamId,setTeamId]=useState(""),[analysisId,setAnalysisId]=useState(""),[session,setSession]=useState<any>(null),[details,setDetails]=useState<any>(null),[positions,setPositions]=useState<any[]>([]),[sharing,setSharing]=useState<any>(null),[message,setMessage]=useState(""),[showPositions,setShowPositions]=useState(true),[observation,setObservation]=useState(""),[assignee,setAssignee]=useState(""),[waypoint,setWaypoint]=useState(""),[assignmentTitle,setAssignmentTitle]=useState("");
 const watch=useRef<any>(null),seq=useRef(0),timer=useRef<any>(null);
 const stopLocal=async()=>{watch.current?.remove();watch.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;await stopSarBackground().catch(()=>{})};
 const refresh=async(s=session)=>{if(!s)return;try{const[d,p]=await Promise.all([fetchSarSession(s.id),fetchSarPositions(s.id)]);setDetails(d);setPositions(p.items||[]);setMessage("Connected · authorized polling fallback active")}catch{setMessage("Access revoked or session unavailable.");setSharing(null);stopLocal()}};
 const poll=(s:any)=>{if(timer.current)clearInterval(timer.current);timer.current=setInterval(()=>refresh(s),3000);refresh(s)};
 useEffect(()=>()=>{stopLocal()},[]);
 const startShare=async(background=false)=>{const fg=await Location.requestForegroundPermissionsAsync();if(fg.status!=="granted"){setMessage("Foreground location permission was not granted.");return}const part=(await startSarSharing(session.id,background)).participant;setSharing(part);seq.current=0;const sharingSessionId=part.sharingSessionId||part.sharing_session_id;if(background){await startSarBackground({sessionId:session.id,sharingSessionId,sequence:0});setMessage("LIVE SHARING ACTIVE · background indicator enabled")}else{watch.current=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,timeInterval:5000,distanceInterval:5},async loc=>{try{await publishSarPosition(session.id,nextSarPosition(loc.coords,sharingSessionId,seq.current++));refresh()}catch{setMessage("Sharing stopped after authorization or network loss.");setSharing(null);stopLocal()}});setMessage("LIVE SHARING ACTIVE · foreground only")}};
 const markers=positions.map((p,i)=>({p,left:12+(i%4)*70,top:12+Math.floor(i/4)*55}));
 return <View style={s.card}><Text style={s.title}>Live SAR Coordination</Text><Text style={s.warning}>Terrain intelligence does not replace incident command, emergency services, training, or official procedures.</Text><Text style={s.meta}>Sharing is explicit and stoppable. Background permission is requested separately and may increase battery use.</Text><Pressable style={s.button} onPress={async()=>{await stopLocal();onClose()}}><Text>Close</Text></Pressable>
 <TextInput style={s.input} value={teamId} onChangeText={setTeamId} placeholder="Team ID"/><TextInput style={s.input} value={analysisId} onChangeText={setAnalysisId} placeholder="Analysis ID"/><View style={s.row}><Pressable style={s.button} onPress={async()=>{const r=await fetchActiveSarSession(teamId,analysisId);setSession(r.session);if(r.session)poll(r.session)}}><Text>Find active</Text></Pressable><Pressable style={s.primary} onPress={async()=>{const next=(await startSarSession({teamId,analysisJobId:analysisId})).session;setSession(next);poll(next)}}><Text>Start session</Text></Pressable></View>
 {session&&<><Text style={s.meta}>Session {session.id} · {details?.accessRole||""}</Text><View style={s.row}>{sharing?<><Text style={s.live}>● LIVE SHARING ACTIVE</Text><Pressable style={s.danger} onPress={async()=>{await stopSarSharing(session.id);await stopLocal();setSharing(null);setMessage("Live sharing stopped.")}}><Text>Stop sharing</Text></Pressable></>:<><Pressable style={s.primary} onPress={()=>startShare(false)}><Text>Start foreground sharing</Text></Pressable><Pressable style={s.button} onPress={()=>startShare(true)}><Text>Enable background sharing</Text></Pressable></>}<Pressable style={s.button} onPress={()=>setShowPositions(v=>!v)}><Text>{showPositions?"Hide":"Show"} Team Positions</Text></Pressable></View>
 {showPositions&&<View style={s.map}>{markers.map(({p,left,top})=>{const state=sarPositionState(p);return <View key={p.userId||p.user_id} style={[s.marker,{left,top,opacity:state.stale?.45:1}]}><Text style={s.markerText}>● {p.displayName||p.display_name||p.email||"Member"}</Text><Text style={s.markerMeta}>{state.stale?"STALE":"current"} · ±{Math.round(p.accuracyMeters||p.accuracy_meters||0)}m</Text></View>})}</View>}
 <Text style={s.subtitle}>Assignments</Text>{(details?.assignments||[]).map((a:any)=><View key={a.id} style={s.item}><Text style={s.meta}>{a.title} · {a.status}</Text><View style={s.row}><Pressable style={s.button} onPress={async()=>{const r=await updateSarAssignmentOffline(analysisId,session.id,a.id,"in_progress");setMessage(r.queued?"Assignment update pending encrypted offline sync.":"Assignment updated.");refresh()}}><Text>Start</Text></Pressable><Pressable style={s.button} onPress={async()=>{const r=await updateSarAssignmentOffline(analysisId,session.id,a.id,"complete");setMessage(r.queued?"Assignment update pending encrypted offline sync.":"Assignment updated.");refresh()}}><Text>Complete</Text></Pressable></View></View>)}
 {["owner","coordinator"].includes(details?.accessRole)&&<><TextInput style={s.input} value={assignee} onChangeText={setAssignee} placeholder="Assigned member user ID"/><TextInput style={s.input} value={waypoint} onChangeText={setWaypoint} placeholder="Waypoint ID"/><TextInput style={s.input} value={assignmentTitle} onChangeText={setAssignmentTitle} placeholder="Assignment title"/><Pressable style={s.button} onPress={async()=>{await createSarAssignment(session.id,{assignedUserId:assignee,waypointId:waypoint,title:assignmentTitle});setAssignmentTitle("");refresh()}}><Text>Create assignment</Text></Pressable></>}
 <TextInput style={s.input} value={observation} onChangeText={setObservation} placeholder="Team observation"/><Pressable style={s.button} onPress={async()=>{const r=await createSarObservationOffline(analysisId,session.id,{clientOperationId:Crypto.randomUUID(),body:observation,clientTimestamp:new Date().toISOString()});setObservation("");setMessage(r.queued?"Observation pending encrypted offline sync.":"Observation synchronized.")}}><Text>Add observation</Text></Pressable><Pressable style={s.danger} onPress={async()=>{await endSarSession(session.id);await stopLocal();setSession(null);setSharing(null)}}><Text>End SAR session</Text></Pressable></>}{!!message&&<Text style={s.meta}>{message}</Text>}</View>;
}
const s=StyleSheet.create({card:{backgroundColor:"#172016",padding:16,borderRadius:16,gap:10},title:{color:"#eef3e8",fontSize:22,fontWeight:"800"},subtitle:{color:"#eef3e8",fontSize:17,fontWeight:"800"},warning:{color:"#f0c784",fontWeight:"700"},meta:{color:"#b5c0ae"},live:{color:"#9bdb87",fontWeight:"900"},input:{backgroundColor:"#edf1e9",padding:12,borderRadius:8},row:{flexDirection:"row",flexWrap:"wrap",gap:8},button:{backgroundColor:"#ccd6c4",padding:10,borderRadius:8},primary:{backgroundColor:"#99b583",padding:12,borderRadius:8},danger:{backgroundColor:"#c87568",padding:10,borderRadius:8},map:{height:180,backgroundColor:"#243124",borderRadius:12,position:"relative"},marker:{position:"absolute"},markerText:{color:"#eef3e8",fontWeight:"800",fontSize:11},markerMeta:{color:"#c7d0c0",fontSize:9},item:{backgroundColor:"#263126",padding:10,borderRadius:8,gap:6}});
