import React, { useEffect, useRef, useState } from "react";
import * as Crypto from "expo-crypto";
import * as Location from "expo-location";
import { ActivityIndicator, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { createSarAssignment, createSarObservationOffline, endSarSession, fetchActiveSarSession, fetchAnalyses, fetchSarPositions, fetchSarSession, fetchTeams, publishSarPosition, startSarSession, startSarSharing, stopSarSharing, updateSarAssignmentOffline } from "./api";
import { ensureForegroundLocationPermission } from "./location-control";
import { nextSarPosition, sarPositionState } from "./sar-core";
import { startSarBackground, stopSarBackground } from "./sar-background";

export function SarScreen({onClose}:{onClose:()=>void}) {
 const [teamId,setTeamId]=useState(""),[analysisId,setAnalysisId]=useState(""),[session,setSession]=useState<any>(null),[details,setDetails]=useState<any>(null),[positions,setPositions]=useState<any[]>([]),[sharing,setSharing]=useState<any>(null),[message,setMessage]=useState(""),[showPositions,setShowPositions]=useState(true),[observation,setObservation]=useState(""),[assignee,setAssignee]=useState(""),[waypoint,setWaypoint]=useState(""),[assignmentTitle,setAssignmentTitle]=useState("");
 const [teams,setTeams]=useState<any[]>([]),[analyses,setAnalyses]=useState<any[]>([]),[loading,setLoading]=useState(true);
 const watch=useRef<any>(null),seq=useRef(0),timer=useRef<any>(null);
 const stopLocal=async()=>{watch.current?.remove();watch.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;await stopSarBackground().catch(()=>{})};
 const refresh=async(s=session)=>{if(!s)return;try{const[d,p]=await Promise.all([fetchSarSession(s.id),fetchSarPositions(s.id)]);setDetails(d);setPositions(p.items||[]);setMessage("Connected · authorized polling fallback active")}catch{setMessage("Access revoked or session unavailable.");setSharing(null);stopLocal()}};
 const poll=(s:any)=>{if(timer.current)clearInterval(timer.current);timer.current=setInterval(()=>refresh(s),3000);refresh(s)};
 useEffect(()=>{Promise.all([fetchTeams(),fetchAnalyses(1,50)]).then(([t,a])=>{setTeams(t.items||[]);setAnalyses(a.items||[])}).catch(()=>setMessage("Teams and analyses could not be loaded. Try again.")).finally(()=>setLoading(false));return()=>{void stopLocal()}},[]);
 const startShare=async(background=false)=>{const fg=await ensureForegroundLocationPermission(Location);if(fg.status!=="granted"){setMessage(fg.status==="unavailable"?"Location permission could not be checked. Try again.":"Foreground location permission is required to share your location.");return}const part=(await startSarSharing(session.id,background)).participant;setSharing(part);seq.current=0;const sharingSessionId=part.sharingSessionId||part.sharing_session_id;if(background){try{await startSarBackground({sessionId:session.id,sharingSessionId,sequence:0});setMessage("LIVE SHARING ACTIVE · ongoing notification enabled")}catch{await stopSarSharing(session.id).catch(()=>{});setSharing(null);setMessage("Live SAR sharing could not start. Keep the app visible and try again.")}}else{watch.current=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,timeInterval:5000,distanceInterval:5},async loc=>{try{await publishSarPosition(session.id,nextSarPosition(loc.coords,sharingSessionId,seq.current++));refresh()}catch{setMessage("Sharing stopped after authorization or network loss.");setSharing(null);stopLocal()}});setMessage("LIVE SHARING ACTIVE · foreground only")}};
 const markers=positions.map((p,i)=>({p,left:12+(i%4)*70,top:12+Math.floor(i/4)*55}));
 return <View style={s.card}><Text style={s.eyebrow}>AUTHORIZED TEAM COORDINATION</Text><Text style={s.title}>Live SAR Coordination</Text><Text style={s.warning}>Terrain intelligence does not replace incident command, emergency services, training, or official procedures.</Text><Text style={s.meta}>Sharing starts only when you choose it, remains visible through an ongoing notification, and is always stoppable.</Text><Pressable accessibilityRole="button" accessibilityLabel={Platform.OS==="ios"?"Close Live SAR":"Back to Home"} style={s.button} onPress={async()=>{await stopLocal();onClose()}}><Text style={s.buttonText}>{Platform.OS==="ios"?"Close":"Back"}</Text></Pressable>
 {loading&&<View accessibilityRole="progressbar" style={s.loading}><ActivityIndicator color="#d0a65d"/><Text style={s.meta}>Loading authorized teams and analyses…</Text></View>}
 <Text style={s.subtitle}>Choose a team</Text><View style={s.row}>{teams.map((team:any)=><Pressable accessibilityRole="button" accessibilityState={{selected:teamId===team.id}} key={team.id} style={teamId===team.id?s.primary:s.button} onPress={()=>setTeamId(team.id)}><Text>{team.name}</Text></Pressable>)}</View>{!teams.length&&<Text style={s.meta}>No teams are available.</Text>}
 <Text style={s.subtitle}>Choose a saved analysis</Text><View style={s.row}>{analyses.map((item:any)=><Pressable accessibilityRole="button" accessibilityState={{selected:analysisId===item.analysisJobId}} key={item.analysisJobId} style={analysisId===item.analysisJobId?s.primary:s.button} onPress={()=>setAnalysisId(item.analysisJobId)}><Text>{item.name||"Terrain Analysis"}</Text></Pressable>)}</View>{!analyses.length&&<Text style={s.meta}>No saved analyses are available.</Text>}
 <View style={s.row}><Pressable accessibilityRole="button" disabled={!teamId||!analysisId} style={[s.button,(!teamId||!analysisId)&&s.disabled]} onPress={async()=>{const r=await fetchActiveSarSession(teamId,analysisId);setSession(r.session);if(r.session)poll(r.session);else setMessage("No active SAR session was found.")}}><Text>Find Active Session</Text></Pressable><Pressable accessibilityRole="button" disabled={!teamId||!analysisId} style={[s.primary,(!teamId||!analysisId)&&s.disabled]} onPress={async()=>{const next=(await startSarSession({teamId,analysisJobId:analysisId})).session;setSession(next);poll(next)}}><Text>Start Session</Text></Pressable></View>
 {session&&<><Text style={s.meta}>Connected · {details?.accessRole||"authorized member"}</Text><View style={s.row}>{sharing?<><Text style={s.live}>● LIVE SHARING ACTIVE</Text><Pressable accessibilityRole="button" style={s.danger} onPress={async()=>{await stopSarSharing(session.id);await stopLocal();setSharing(null);setMessage("Live sharing stopped.")}}><Text>Stop sharing</Text></Pressable></>:<><Pressable accessibilityRole="button" style={s.primary} onPress={()=>startShare(false)}><Text>Start foreground sharing</Text></Pressable><Pressable accessibilityRole="button" style={s.button} onPress={()=>startShare(true)}><Text>Enable background sharing</Text></Pressable></>}<Pressable accessibilityRole="button" accessibilityState={{expanded:showPositions}} style={s.button} onPress={()=>setShowPositions(v=>!v)}><Text>{showPositions?"Hide":"Show"} Team Positions</Text></Pressable></View>
 {showPositions&&<View style={s.map}>{markers.length?markers.map(({p,left,top})=>{const state=sarPositionState(p);return <View key={p.userId||p.user_id} style={[s.marker,{left,top,opacity:state.stale?.45:1}]}><Text style={s.markerText}>● {p.displayName||p.display_name||p.email||"Member"}</Text><Text style={s.markerMeta}>{state.stale?"STALE":"current"} · ±{Math.round(p.accuracyMeters||p.accuracy_meters||0)}m</Text></View>}):<Text style={s.emptyMap}>No team positions have been shared.</Text>}</View>}
 <Text style={s.subtitle}>Assignments</Text>{(details?.assignments||[]).map((a:any)=><View key={a.id} style={s.item}><Text style={s.meta}>{a.title} · {a.status}</Text><View style={s.row}><Pressable accessibilityRole="button" style={s.button} onPress={async()=>{const r=await updateSarAssignmentOffline(analysisId,session.id,a.id,"in_progress");setMessage(r.queued?"Assignment update pending encrypted offline sync.":"Assignment updated.");refresh()}}><Text>Start</Text></Pressable><Pressable accessibilityRole="button" style={s.button} onPress={async()=>{const r=await updateSarAssignmentOffline(analysisId,session.id,a.id,"complete");setMessage(r.queued?"Assignment update pending encrypted offline sync.":"Assignment updated.");refresh()}}><Text>Complete</Text></Pressable></View></View>)}
 {__DEV__&&["owner","coordinator"].includes(details?.accessRole)&&<><Text style={s.warning}>Development assignment diagnostics</Text><TextInput style={s.input} value={assignee} onChangeText={setAssignee} placeholder="Assigned member user ID"/><TextInput style={s.input} value={waypoint} onChangeText={setWaypoint} placeholder="Waypoint ID"/><TextInput style={s.input} value={assignmentTitle} onChangeText={setAssignmentTitle} placeholder="Assignment title"/><Pressable accessibilityRole="button" style={s.button} onPress={async()=>{await createSarAssignment(session.id,{assignedUserId:assignee,waypointId:waypoint,title:assignmentTitle});setAssignmentTitle("");refresh()}}><Text>Create assignment</Text></Pressable></>}
 <TextInput accessibilityLabel="Team observation" style={s.input} value={observation} onChangeText={setObservation} placeholder="Team observation"/><Pressable accessibilityRole="button" style={s.button} onPress={async()=>{const r=await createSarObservationOffline(analysisId,session.id,{clientOperationId:Crypto.randomUUID(),body:observation,clientTimestamp:new Date().toISOString()});setObservation("");setMessage(r.queued?"Observation pending encrypted offline sync.":"Observation synchronized.")}}><Text>Add observation</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="End SAR session" style={s.danger} onPress={async()=>{await endSarSession(session.id);await stopLocal();setSession(null);setSharing(null)}}><Text>End SAR session</Text></Pressable></>}{!!message&&<Text accessibilityLiveRegion="polite" style={s.meta}>{message}</Text>}</View>;
}
const s=StyleSheet.create({card:{width:"100%",maxWidth:900,alignSelf:"center",backgroundColor:"#172016",padding:18,borderRadius:20,gap:14,borderWidth:1,borderColor:"#334333"},eyebrow:{color:"#d0a65d",fontSize:11,fontWeight:"800",letterSpacing:1.5},title:{color:"#eef3e8",fontSize:28,fontWeight:"900"},subtitle:{color:"#eef3e8",fontSize:18,fontWeight:"800",marginTop:6},warning:{color:"#f0c784",fontWeight:"700",lineHeight:21,backgroundColor:"#2c2419",borderRadius:14,padding:12,borderWidth:1,borderColor:"#514027"},meta:{color:"#b5c0ae",lineHeight:20},live:{color:"#9bdb87",fontWeight:"900",minHeight:48,textAlignVertical:"center"},input:{color:"#10140f",backgroundColor:"#edf1e9",paddingHorizontal:14,paddingVertical:12,borderRadius:12,minHeight:48,fontSize:16},row:{flexDirection:"row",flexWrap:"wrap",gap:8},button:{backgroundColor:"#ccd6c4",paddingHorizontal:14,paddingVertical:12,borderRadius:12,minHeight:48,justifyContent:"center",alignItems:"center"},primary:{backgroundColor:"#99b583",paddingHorizontal:14,paddingVertical:12,borderRadius:12,minHeight:48,justifyContent:"center",alignItems:"center"},danger:{backgroundColor:"#c87568",paddingHorizontal:14,paddingVertical:12,borderRadius:12,minHeight:48,justifyContent:"center",alignItems:"center"},buttonText:{color:"#142012",fontWeight:"800"},disabled:{opacity:.4},loading:{minHeight:96,alignItems:"center",justifyContent:"center",gap:10},map:{height:240,backgroundColor:"#243124",borderRadius:16,position:"relative",alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#3b4b3a"},emptyMap:{color:"#b5c0ae",padding:16,textAlign:"center"},marker:{position:"absolute"},markerText:{color:"#eef3e8",fontWeight:"800",fontSize:11},markerMeta:{color:"#c7d0c0",fontSize:10},item:{backgroundColor:"#263126",padding:14,borderRadius:14,gap:8,borderWidth:1,borderColor:"#3b4b3a"}});
